server:
 port: 8085

app:
  logging-to: console  #options are :console/file
  drone: 
    video-ws-endpoint: /videofeed
    control-server-port: 1314
    video-server-port: 1313 #one bite size. As you know from the raspi, data sent to ws from raspi contains 1 byte drone id and rest img udp data
    drone-id-length: 1 # Amount of symbols
    default-altitude: 4
    default-speed: 15
    host-privateip: 192.168.1.7
    
logging:
  level:
    org.springFramework: INFO
    com.odafa.dronecloudapp: DEBUG